name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcloud-service-key.json

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json" >> $GITHUB_ENV

    - name: Configure gcloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
      run: gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json

    - name: Set Google Cloud Project
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
      run: gcloud config set project neural-journey-377617

    - name: Deploy to Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
      run: |
        # Add your deployment commands here
        echo "Deploying to Google Cloud..."
