name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode service account key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcloud-service-key.json
        if [ ! -s $HOME/gcloud-service-key.json ]; then
          echo "Failed to create service account key file."
          exit 1
        fi

    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json

    - name: Set Google Cloud Project
      run: gcloud config set project neural-journey-377617

    - name: Deploy to Google Cloud
      run: |
        echo "Deploying to Google Cloud..."
        # Add your deployment commands here
