name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Write service account key to file
      run: echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-service-key.json

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json" >> $GITHUB_ENV

    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json

    - name: Set Google Cloud Project
      run: gcloud config set project neural-journey-377617

    - name: Deploy to Google Cloud
      run: |
        echo "Deploying to Google Cloud..."
        # Add your deployment commands here
