name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Set Google Cloud Project
      run: gcloud config set project neural-journey-377617

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json" >> $GITHUB_ENV

    - name: Deploy to Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
      run: |
        # Add your deployment commands here
        echo "Deploying to Google Cloud..."
