name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create service account key file
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | sed 's/^/"/;s/$/"/;s/: /": "/g;s/, /", "/g;s/\\n/\\n/g' > $HOME/gcloud-service-key.json
          echo "Service account key file created."

      - name: Check JSON content with line numbers
        run: |
          echo "Contents of gcloud-service-key.json with line numbers:"
          nl -ba $HOME/gcloud-service-key.json

      - name: Validate JSON format
        run: |
          echo "Validating JSON format..."
          if ! jq empty $HOME/gcloud-service-key.json; then
            echo "Invalid JSON format."
            exit 1
          fi
          echo "JSON format is valid."

      - name: Authenticate with Google Cloud
        run: |
          echo "Authenticating with Google Cloud..."
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json

      - name: Set Google Cloud project
        run: |
          echo "Setting Google Cloud project..."
          gcloud config set project neural-journey-377617

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here

      - name: Cleanup
        run: |
          echo "Cleaning up..."
          rm $HOME/gcloud-service-key.json
